from typing import Any, Protocol


class ConversationRepository(Protocol):
    def create(self, *, user_id: str, question: str, equipment_name: str | None) -> Any: ...

    def get(self, conversation_id: str) -> Any | None: ...

    def get_for_user(self, user_id: str, conversation_id: str) -> Any | None: ...

    def list_recent(self, limit: int = 50) -> list[Any]: ...

    def save(self, conversation: Any) -> None: ...
